FROM eclipse-temurin:25-jre@sha256:681c543d6f36c50f45e9b5226930a46203dcfa351d3670e9d0bdf0dabae53539

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 libstdc++6 curl && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*

WORKDIR /app

COPY build/libs/whisper-spring-server-*.jar whisper-spring-server.jar

HEALTHCHECK --interval=5s --timeout=2s --start-period=15s --retries=5 \
  CMD curl --fail http://localhost:8080/actuator/health || exit 1

CMD ["java", "-jar", "whisper-spring-server.jar"]
