FROM nvidia/cuda:13.3.1-base-ubuntu26.04@sha256:30f7a2345973fbb584f4c8bc9a7c16c7bae6d0ec08883df4e030387d74756292

ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    libcublas-13-3 \
    libgomp1 \
    openjdk-25-jre-headless \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/*

WORKDIR /app

COPY build/libs/whisper-spring-server-*.jar whisper-spring-server.jar

HEALTHCHECK --interval=5s --timeout=2s --start-period=15s --retries=5 \
  CMD curl --fail http://localhost:8080/actuator/health || exit 1

CMD ["java", "-jar", "whisper-spring-server.jar"]
