services:
  whisper-spring-server:
    image: ghcr.io/ferdinandmehlan/whisper-spring-server:${TAG:-dev}
    container_name: whisper-spring-server
    build:
      context: ./whisper-spring-server
      dockerfile: Containerfile
    ports:
      - "8080:8080"
    environment:
      WHISPER_MODEL_PATH: "models/ggml-tiny.bin"
    volumes:
      - ./models:/app/models
