services:
  whisper-spring-server:
    image: ghcr.io/ferdinandmehlan/whisper-spring-server:${TAG:-dev-cuda}
    container_name: whisper-spring-server
    build:
      context: ./server
      dockerfile: Containerfile.cuda
    ports:
      - "8080:8080"
    environment:
      WHISPER_MODEL_PATH: "models/ggml-tiny.bin"
    volumes:
      - ./models:/app/models
    # For gpus to be accessible by containers the NVIDIA Container Toolkit needs to be installed
    # Attaching gpus for podman
    devices:
      - nvidia.com/gpu=all
    # Attaching gpus for docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
