services:
  whisper-spring-server:
    image: ghcr.io/ferdinandmehlan/whisper-spring-server:${TAG:-dev-cuda}
    container_name: whisper-spring-server
    build:
      context: ./whisper-spring-server
      dockerfile: Containerfile.cuda
    ports:
      - "8080:8080"
    volumes:
      - ./models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
